version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - C:\_elk\data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - 5046:5046
    volumes:
      - C:\_elk\logstash_configs\pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - C:\_elk\logstash_configs\pipelines:/usr/share/logstash/config/pipelines:ro

volumes:
  elasticsearch:
    driver: local